<?php

namespace TicketBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function findIdsAndTitles() {
        $qb = $this->createQueryBuilder('t')
            ->select('t.id', 't.title');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
