<?php

namespace TicketBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findIdsAndNames() {
        $qb = $this->createQueryBuilder('u')
            ->select('u.id', 'u.username');

        $query = $qb->getQuery();

        return $query->getResult();
    }

    public function findUsersById($ids) {
        $users = [];

        foreach($ids as $id) {
            $qb = $this->createQueryBuilder('u')
                ->where('u.id = :id')
                ->setParameter('id', $id);

            $query = $qb->getQuery();

            array_push($users, $query->getResult()[0]);
        }

        return $users;
    }
}
